name: Build and Deploy WAR on GitHub Actions (Manual Tomcat Install)

on:
  push:
    branches:
      - main  # Runs only when code is pushed to the main branch
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build the WAR File with Maven
        run: mvn clean package -DskipTests

      - name: Upload WAR Artifact (For Later Use)
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: target/*.war

      - name: Download and Install Apache Tomcat 9 Manually
        run: |
          TOMCAT_VERSION=9.0.80
          wget https://downloads.apache.org/tomcat/tomcat-9/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz
          tar -xvzf apache-tomcat-$TOMCAT_VERSION.tar.gz
          sudo mv apache-tomcat-$TOMCAT_VERSION /opt/tomcat
          sudo chmod +x /opt/tomcat/bin/*.sh
          echo "Tomcat installed successfully."

      - name: Deploy WAR to Tomcat
        run: |
          sudo cp target/*.war /opt/tomcat/webapps/
          /opt/tomcat/bin/startup.sh
          echo "WAR file deployed on GitHub Actions server"

      - name: Verify Deployment (Check if Tomcat is Running)
        run: |
          sleep 10  # Wait for Tomcat to start
          curl -I http://localhost:8080/ || echo "Deployment check failed"
