name: Deploy WAR on GitHub Actions (Temporary Server)

on:
  push:
    branches:
      - main  # Runs only when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build the WAR File
        run: mvn clean package -DskipTests

      - name: Install Tomcat 9
        run: sudo apt-get install -y tomcat9 tomcat9-admin tomcat9-common

      - name: Deploy WAR to Tomcat
        run: |
          sudo cp target/*.war /var/lib/tomcat9/webapps/
          sudo systemctl restart tomcat9
          echo "WAR file deployed on GitHub Actions server"

      - name: Verify Deployment
        run: |
          sleep 10  # Wait for Tomcat to start
          curl -I http://localhost:8080/ || echo "Deployment check failed"
