name: Java Maven WAR Deployment

on:
  push:
    branches:
      - main  # Runs when pushing to main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Store WAR File
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload WAR File as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: war-file
          path: target/*.war

  release:
    name: Publish WAR to GitHub Releases
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download WAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: war-file
          path: target/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.war
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: "Automated WAR deployment."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
